apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (a9d05d509)
  creationTimestamp: null
  labels:
    io.kompose.service: strapi
  name: eshop-cms
  namespace: web
spec:
  type: NodePort
  ports:
    - nodePort: 32410
      protocol: TCP
      name: "1337"
      port: 80
      targetPort: 1337
  selector:
    io.kompose.service: strapi
