---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: init-script
  namespace: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-data-pvc
  namespace: db
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-strapi
  namespace: db
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: strapi
        - name: MYSQL_PASSWORD
          value: strapi
        - name: MYSQL_ROOT_PASSWORD
          value: strapi
        - name: MYSQL_USER
          value: strapi
        image: mysql
        args: ["--default-authentication-plugin=mysql_native_password"]
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: data
        - mountPath: /docker-entrypoint-initdb.d
          name: init-script
      initContainers:
      - args:
        - -o
        - /tmp/data/init.sql
        - https://setnext-eshop.s3.amazonaws.com/strapi/mysql_backup/strapi_backup_31_jan_2023.sql
        image: appropriate/curl
        name: init-script-downloader
        volumeMounts:
        - mountPath: /tmp/data
          name: init-script
#      nodeSelector:
 #       zone: secured
      volumes:
      - name: init-script
        persistentVolumeClaim:
          claimName: init-script
      - name: data
        persistentVolumeClaim:
          claimName: mysql-data-pvc
