# An example of ClusterConfig object using Managed Nodes
---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: eshop-eks-cluster
  region: us-east-1

managedNodeGroups:
  - name: eshop-ng-public
    instanceType: t3.large
    minSize: 3
    desiredCapacity: 3
    maxSize: 3
    volumeSize: 10
    updateConfig:
      maxUnavailable: 3 # or `maxUnavailablePercentage: 75` to specify maxUnavailable as a percentage of total nodes
    labels: {zone: public}
    tags:
      nodegroup-role: worker
