apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongo-sa-rolebinding
  namespace: db 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sa-role 
subjects:
- namespace: webapps 
  kind: ServiceAccount
  name: mongo-replication-helper-sa 
