apiVersion: v1
kind: Service
metadata:
  labels:
    app: eshop-standalone
  name: eshop
spec:
  type: LoadBalancer
  ports:
    - nodePort: 30950
      protocol: TCP
      name: "80"
      port: 80
      targetPort: 80
  selector:
    app: eshop-standalone

